"""empty message

Revision ID: 38686b1c89a2
Revises: ca3e98622bdf
Create Date: 2025-02-09 02:27:27.354069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38686b1c89a2'
down_revision = 'ca3e98622bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('unit_price', sa.Float(precision=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
